from __future__ import annotations

import frappe

CASHIER_ROLE = "Mobile POS Cashier"


def make_cashier(email: str) -> str:
	"""Create (or reset) an enabled Frappe User with only the Mobile POS Cashier role."""
	if frappe.db.exists("User", email):
		frappe.delete_doc("User", email, force=True)
	user = frappe.get_doc(
		{
			"doctype": "User",
			"email": email,
			"first_name": email.split("@")[0].title(),
			"enabled": 1,
			"user_type": "Website User",
			"roles": [{"role": CASHIER_ROLE}],
		}
	)
	user.flags.ignore_validate = True
	user.flags.ignore_links = True
	user.insert(ignore_permissions=True)
	return email


def make_pos_profile(
	name: str,
	*,
	company: str,
	warehouse: str,
	customer: str,
	user: str,
	currency: str = "IDR",
	selling_price_list: str | None = None,
	disabled: int = 0,
) -> str:
	"""Insert a minimal POS Profile assigned to ``user`` (bypassing ERPNext validate)."""
	if frappe.db.exists("POS Profile", name):
		frappe.delete_doc("POS Profile", name, force=True)
	doc = frappe.get_doc(
		{
			"doctype": "POS Profile",
			"name": name,
			"company": company,
			"warehouse": warehouse,
			"customer": customer,
			"currency": currency,
			"selling_price_list": selling_price_list or "Standard Selling",
			"disabled": disabled,
			"applicable_for_users": [{"user": user}],
		}
	)
	doc.flags.ignore_validate = True
	doc.flags.ignore_links = True
	doc.insert(ignore_permissions=True, ignore_mandatory=True, ignore_links=True)
	return name


def make_opening_entry(
	*,
	user: str,
	company: str,
	pos_profile: str,
	period_start_date,
	posting_date,
	balances=None,
	status: str = "Open",
) -> str:
	"""Insert a POS Opening Entry and mark it submitted/Open for read tests.

	The name is generated by ERPNext's autoname; the returned name is the actual
	document name, so callers (and the read scaffold) can find it.
	"""
	doc = frappe.get_doc(
		{
			"doctype": "POS Opening Entry",
			"user": user,
			"company": company,
			"pos_profile": pos_profile,
			"period_start_date": period_start_date,
			"posting_date": posting_date,
			"balance_details": balances or [{"mode_of_payment": "Cash", "opening_amount": 0}],
			"status": status,
		}
	)
	doc.flags.ignore_validate = True
	doc.flags.ignore_links = True
	doc.insert(ignore_permissions=True, ignore_mandatory=True, ignore_links=True)
	name = doc.name
	# Submit bypassing the controller so read-scaffold tests do not require accounts.
	frappe.db.set_value("POS Opening Entry", name, "docstatus", 1, update_modified=False)
	frappe.db.set_value("POS Opening Entry", name, "status", status, update_modified=False)
	return name


def make_oauth_client(client_id: str) -> str:
	"""Create a public Mobile POS OAuth Client (no usable secret for Android)."""
	if frappe.db.exists("OAuth Client", client_id):
		frappe.delete_doc("OAuth Client", client_id, force=True)
	doc = frappe.get_doc(
		{
			"doctype": "OAuth Client",
			"client_id": client_id,
			"app_name": "Mobile POS Test",
			"grant_type": "Authorization Code",
			"response_type": "Code",
			"skip_authorization": 0,
			"scopes": "all",
			"redirect_uris": "https://localhost/callback",
			"default_redirect_uri": "https://localhost/callback",
			"token_endpoint_auth_method": "None",
			"allowed_roles": [{"role": CASHIER_ROLE}],
		}
	)
	doc.flags.ignore_validate = True
	doc.flags.ignore_links = True
	doc.insert(ignore_permissions=True, ignore_mandatory=True, ignore_links=True)
	return client_id


def make_bearer_token(token: str, *, client_id: str, user: str, status: str = "Active") -> str:
	"""Insert an OAuth Bearer Token row for auth-hook lookups."""
	if frappe.db.exists("OAuth Bearer Token", token):
		frappe.delete_doc("OAuth Bearer Token", token, force=True)
	doc = frappe.get_doc(
		{
			"doctype": "OAuth Bearer Token",
			"access_token": token,
			"client": client_id,
			"user": user,
			"scopes": "all",
			"status": status,
			"expiration_time": "2099-12-31 23:59:59",
			"expires_in": 3600,
		}
	)
	doc.flags.ignore_validate = True
	doc.flags.ignore_links = True
	doc.insert(ignore_permissions=True, ignore_mandatory=True, ignore_links=True)
	return token


class FakeRequest:
	"""Minimal stand-in for Werkzeug's request used by the auth hook."""

	host = "localhost"
	scheme = "https"

	def __init__(self, path: str, method: str = "GET", headers: dict | None = None) -> None:
		self.path = path
		self.method = method
		self.headers = headers or {}


def set_request(path: str, method: str = "GET", headers: dict | None = None) -> None:
	frappe.local.request = FakeRequest(path, method, headers)


def clear_fake_request() -> None:
	if isinstance(getattr(frappe.local, "request", None), FakeRequest):
		delattr(frappe.local, "request")


def clear_mobile_pos_request_table() -> None:
	frappe.db.delete("Mobile POS Request")


def make_customer_group(
	group_name: str, *, parent_customer_group: str = "All Customer Groups"
) -> str:
	"""Insert a leaf Customer Group for closure tests."""
	if frappe.db.exists("Customer Group", group_name):
		frappe.delete_doc("Customer Group", group_name, force=True)
	doc = frappe.get_doc(
		{
			"doctype": "Customer Group",
			"customer_group_name": group_name,
			"parent_customer_group": parent_customer_group,
			"is_group": 0,
		}
	)
	doc.flags.ignore_validate = True
	doc.flags.ignore_links = True
	doc.insert(ignore_permissions=True)
	return doc.name
